//Arrays
const PrefArray = ["Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Fukushima","Gifu","Gunma","Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima","Kanagawa","Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata","Oita","Okayama","Osaka","Saga","Saitama","Shiga","Shimane","Shizuoka","Tochigi","Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi"];
const DetailedPrefArray = [
    ["Agui","Aisai","Ama","Anjo","Chiryu","Chita","Fuso","Gamagori","Handa","Hekinan","Higashiura","Ichinomiya","Inazawa","Inuyama","Iwakura","Kanie","Kariya","Kasugai","Kitanagoya","Kiyosu","Komaki","Konan","Kota","Mihama","Minamichita","Miyoshi","Nagakute","Nagoya_1","Nagoya_2","Nishio","Nisshin","Obu","Oguchi","Oharu","Okazaki","Owariasahi","Seto","Shinshiro","Shitara","Tahara","Takahama","Taketoyo","Tobishima","Toei","Togo","Tokai","Tokoname","Toyoake","Toyohashi","Toyokawa","Toyone","Toyota","Toyoyama","Tsushima","Yatomi"],
    ["Akita","Daisen","Fujisato","Gojome","Hachirogata","Happou","Higashinaruse","Ikawa","Kamikoani","Katagami","Kazuno","Kitaakita","Kosaka","Misato","Mitane","Nikaho","Noshiro","Odate","Oga","Ogata","Semboku","Ugo","Yokote","Yurihonjo","Yuzawa"],
    ["Ajigawasa","Aomori","Fujisaki","Fukaura","Gonohe","GoshogawaraNorth","GoshogawaraSouth","Hachinohe","Hashikami","Higashidoori","Hirakawa","Hiranai","Hirosaki","Imabetsu","Inakadate","Itayanagi","Kazamura","Kuroishi","Misawa","Mutsu","NakadomariNorth","NakadomariSouth","Nanbu","Nishimeya","Noheji","Oirase","Ooma","Owani","Rokkasho","Rokunohe","Sai","Sannohe","Shichinohe","Shingo","SotogahamaNorth","SotogahamaSouth","Takko","Tohoku","Towada","Tsugaru","Tsuruta","Yokohama","Yomogita"],
    ["Abiko","Asahi","Chiba","Chonan","Chosei","Choshi","Funabashi","Futtsu","Ichihara","Ichikawa","Ichinomiya","Inzai","Izumi","Kamagaya","Kamogaya","Kashiwa","Katori","Katsuura","Kimitsu","Kisarazu","Kozaki","Kujukuri","Kyonan","Matsudo","Minamiboso","Mobara","Mutsuzawa","Nagara","Nagareyama","Narashino","Narita","Noda","Oamishirasato","Onjuku","Otaki","Sakae","Sakura","Sammu","Shibayama","Shirako","Shiroi","Shisui","Sodegaura","Sosa","Tako","Tateyama","Togane","Tohnosho","Tomisato","Urayasu","Yachimata","Yachiyo","Yokoshibahikari","Yotsukaido"],
    ["Ainan","Ikata","Imabari","Iyo","Kamijima","Kihoku","Kumakogen","Masaki","Matsuno","Matsuyama","Niihama","Ozu","Saijo","Seiyo","Shikokuchuo","Tobe","Toon","Uchiko","Uwajima","Yawatahama"],
    ["Awara","Echizencho","Echizenshi","Eiheiji","Fukui","Ikeda","Katsuyama","Mihama","Minamiechizen","Obama","Ohi","Ono","Sabae","Sakai","Takahama","Tsuruga","Wakasa"],
    ["Aka","Asakura","Ashiya","Buzen","Chikugo","Chikujo","Chikushino","Chikuzen","Dazaifu","Fukuchi","Fukuoka","Fukutsu","Hirokawa","Hisayama","Iizuka","Itoda","Itoshima","Kama","Kanda","Kasuga","Kasuya","Kawara","Kawasaki","Keisen","Kitakyushu","Koga","Koge","Kotake","Kurate","Kurume","Miyako","Miyama","Miyawaka","Mizumaki","Munataka","Nakagawa","Nakama","Nogata","Ogori","Okagaki","Okawa","Omuta","Onga","Onojo","Ooki","Oto","Sasaguri","Shime","Shingu","Soeda","Sue","Tachiarai","Tagawa","Toho","Ukiha","Umi","Yame","Yanagawa","Yoshitomi","Yukuhashi"],
    ["Aizubange","Aizumisato","Aizuwakamatsu","Asakawa","Bandai","Date","Fukushima_1","Fukushima_2","Fukushima_3","Furudono","Futaba","Hanawa","Hinoemata","Hirata","Hirono","Iitate","Inawashiro","Ishikawa","Iwaki","Izumizaki","Kagamiishi","Kaneyama","Katsurao","Kawamata","Kawauchi","Kitakata","Kitashiobara","Koori","Koriyama","Kunimi","Miharu","Minamiaizu","Minamisoma","Mishima","Motomiya","Nakajima","Namie","Naraha","Nihonmatsu","Nishiaizu","Nishigo","Okuma","Ono","Otama","Samegawa","Shimogo","Shinchi","Shirakawa","Showa","Soma","Sukagawa","Tadami","Tamakawa","Tamura","Tanagura","Tenei","Tomioka","Yabuki","Yamatsuri","Yanaizu","Yugawa"],
    ["Anpachi","Ena","Gero","Gifu","Ginan","Godo","Gujo","Hashima","Hichiso","Hida","Higashishirakawa","Ibigawa","Ikeda","Kaizu","Kakamigahara","KaniNorth","KaniSouth","Kasamatsu","Kawabe","Kitagata","Mino","Minokamo","Mitake","Mizuho","Mizunami","Motosu","Nakatsugawa","OgakiEast","OgakiNorth","OgakiWest","Ono","Sakahogi","Seki","Sekigahara","Shirakawacho","Shirakawamura","Tajimi","Takayama","Tarui","Toki","Tomika","Wanouchi","Yamagata","Yaotsu","Yoro"],
    ["Annaka","Chiyoda","Fujioka","Higashiatsuma","Isesaki","Itakura","Kanna","Kanra","Katashina","Kawaba","KiryuEast","KiryuWest","Kusatsu","Maebashi","Meiwa","Midori","Minakami","Naganohara","Nakanojo","Nanmoku","Numata","Oizumi","Ora","Ota","Shibukawa","Shimonita","Shinto","Showa","TakasakiNorth","TakasakiSouth","Takayama","Tamamura","Tatebayashi","Tomioka","Tsumagoi","Ueno","Yoshioka"],
    ["Akiota","Akitakata","Etajima","Fuchu","Fukuyama_1","Fukuyama_2","Hatsukaichi","Higashihiroshima","Hiroshima_1","Hiroshima_2","Jinsekikogen","Kaita","Kitahiroshima","Kumano","Kure","Mihara","Miyoshi","Onomichi","Osakikamijima","Otake","Saka","Sera","Shobara","Takehara"],
    [],
    ["Aioi","Akashi","Ako","Amagasaki","Asago","Ashiya","Awaji","Fukusaki","Harima","HimejiNorth","HimejiSouth","Ichikawa","Inagawa","Inami","Itami","Kakogawa","Kami","Kamigori","Kamikawa","Kasai","Kato","Kawanishi","Kobe","Miki","Minamiawaji","Nishinomiya","Nishiwaki","Ono","Sanda","Sayo","Shinonsen","Shiso","Sumoto","Taishi","Taka","Takarazuka","Takasago","Tamba","Tambasasayama","Tatsuno","Toyooka","Yabu"],
    ["Ami","Bando","Chikusei","Daigo","Goka","Hitachi","Hitachinaka","Hitachiomiya","Hitachiota","Hokota","Ibaraki","Inashiki","Ishioka","Itako","Joso","Kamisu","Kasama","Kashima","Kasumigaura","Kawachi","Kitaibaraki","Koga","Miho","Mito","Moriya","Naka","Namegata","Oarai","Omitama","Ryugasaki","Sakai","Sakuragawa","Shimotsuma","Shirosato","Takahagi","Tokai","Tone","Toride","Tsuchiura","Tsukuba","Tsukubamirai","Ushiku","Yachiyo","Yuki"],
    ["Anamizu","Hakui","Hakusan","Hodatsushimizu","Kaga","Kahoku","Kanazawa","Kawakita","Komatsu","Nakanoto","Nanao","Nomi","Nonoichi","Noto","Shika","Suzu","Tsubata","Uchinada","Wajima"],
    ["Fudai","Hachimantai","Hanamaki","Hiraizumi","Hirono","Ichinohe","Ichinoseki","Iwaizumi","Iwate","Kamaishi","Kanegasaki","Karumai","Kitakami","Kuji","Kunohe","Kuzumaki","Miyako","Morioka","Ninohe","Nishiwaga","Noda","Ofunato","Oshu","Otsuchi","Rikuzentakata","Shiwa","Shizukuishi","Sumita","Takizawa","Tanohata","Tono","Yahaba","Yamada"],
    ["Ayagawa","Higashikagawa","Kanonji","Kotohira","Manno","Marugame","Miki","Mitoyo","Naoshima","Sakaide","Sanuki","Shodoshima","Tadotsu","Takamatsu","Tonosho","Utazu","Zentsuji"],
    ["Aira","Akune","Higashikushira","Hioki","Ibusuki","Ichikikushikino","Isa","Izumi","Kagoshima","Kanoya","Kimotsuki","Kinko","Kirishima","Makurazaki","Minamikyushu","Minamiosumi","Minamisatsuma","Nagashima","Osaki","Satsuma","Satsumasendai","Shibushi","Soo","Tarumizu","Yusui"],
    ["Aikawa","Atsugi","Ayase","Chigasaki","Ebina","Fujisawa","Hadano","Hakone","Hayama","Hiraitsuka","Isehara","Kaisei","Kamakura","Kawasaki","Kiyokawa","Manazuru","Matsuda","Minamiashigara","Miura","Nakai","Ninomiya","Odawara","Oi","Oiso","Sagamihara","Samukawa","Yamakita","Yamato","Yokohama","Yokosuka_1","Yokosuka_2","Yugawara","Zama","Zushi"],
    ["Aki","Geisei","Hidaka","Ino","Kami","Kitagawa","Kochi","Konan","Kurishio","Mihara","Motoyama","Muroto","Nahari","Nakatosa","Nankoku","Niyodogawa","Ochi","Okawa","Otoyo","Otsuki","Sakawa","Shimantocho","Shimantoshi","Sukumo","Susaki","Tano","Tosa","Tosacho","Tosashimizu","Toyo","Tsuno","Umaji","Yasuda","Yusuhara"],
    ["Amakusa_1","Amakusa_2","Arao","Asagiri","Ashikita","Aso","Gyokuta","Hikawa","Hitoyoshi","Itsuki","Kamiamakusa","Kashima","Kikuchi","Kikuyo","Kosa","Koshi","Kumamoto","Kumamura","Mashiki","Mifune","Minamata","Minamiaso","Minamioguni","Misato","Mizukami","Nagasu","Nagomi","Nankan","Nishihara","Nishiki","Oguni","Ozu","Reihoku","Sagara","Takamori","Tamana","Taragi","Tsunagi","Ubuyama","Uki","Uto","Yamae","Yamaga","Yamato","Yatsushiro","Yunomae"],
    ["Ayabe","Fukuchiyama","Ide","Ine","Joyo","Kameoka","Kasagi","Kizugawa","Kumiyama","Kyotamba","Kyotanabe","Kyotango","Kyoto","Minamiyama","Miyazu","Muko","Nagaokakyo","Nantan","Oyamazaki","Seika","Uji","Ujitawara","Wazuka","Yawata","Yosano"],
    ["Asahi","Iga","Inabe","Ise","Kameyama","Kawagoe","Kiho","Kihoku","Kisosaki","Komono","Kumano","Kuwana","Matsusaka","Meiwa","Mihama","Minamiise","Nabari","Odai","Owase","Shima","Suzuka","Taiki","Taki","Tamaki","Toba","Toin","Tsu","Watarai","Yokkaichi"],
    ["Higashimatsushima","Ishinomaki_1","Ishinomaki_2","Iwanuma","Kakuda","Kami","Kawasaki","Kesennuma_1","Kesennuma_2","Kurihara","Marumori","Matsushima","Minamisanriku","Misato","Murata","Natori","Ogawara","Ohira","Onagawa","Osaki","Osato","Rifu","Sendai","Shibata","Shichigahama","Shichikashuku","Shikama","Shiogama","Shiroishi","Tagajo","Taiwa","Tome","Tomiya","Wakuya","Watari","Yamamoto","Zaou"],
    ["Aya","Ebino","Gokase","Hinokage","Hyuga","Kadogawa","Kawaminami","Kijo","Kobayashi","Kunitomi","Kushima","Mimata","Misato","Miyakonojo","Miyazaki","Morotsuka","Nichinan","Nishimera","Nobeoka","Saito","Shiiba","Shintomi","Takachiho","Takaharu","Takanabe","Tsuno"],
    ["Achi","Agematsu","Anan","Aoki","Asahi","Azumino","Chikuhoku","Chikuma","Chino","Fujimi","Hakuba","Hara","Hiraya","Iida","Iijima","Iiyama","Iizuna","Ikeda","Ikusaka","Ina","Karuizawa","Kawakami","Kijimadaira","Kisomachi","Kisomura","Kitaaiki","Komagane","Komoro","Koumi","Matsukawamachi","Matsukawamura","Matsumoto","Minamiaiki","Minamimaki","Minamiminowa","Minowa","Miyada","Miyota","Nagano","Nagawa","Nagaiso","Nakagawa","Nakano","Neba","Nozawaonsen","Obuse","Ogawa","Okaya","Omachi","Omi","Ookuwa","Ooshika","Otaki","Otari","Sakae","Sakaki","Saku","Sakuho","Shimojo","Shimosuwa","Shinano","Shiojiri","Suwa","Suzaka","Takagi","Takamori","Takayama","Tateshina","Tatsuno","Tenryu","Tomi","Toyooka","Ueda","Urugi","Yamagata","Yamanouchi","Yasuoka"],
    ["Hasami","Higashisonogi","Hirado","Isahaya","Kawatana","Matsuura_1","Matsuura_2","Minamishimabara","Nagasaki","Nagayo","Omura","Saikai","Sasebo","Saza","Shimabara","Togitsu","Unzen"],
    ["Ando","Asukamura","Gojo","Gose","Heguri","Higashiyoshino","Ikaruga","Ikoma","Kamikitayama","Kanmaki","Kashiba","Kashihara","Katsuragi","Kawai","Kawakami","Kawanishi","Koryo","Kurotaki","Mitsue","Miyake","Nara","Nosegawa","Oji","Oyodo","Sakurai","Sango","Shimoichi","Shimokitayama","Soni","Takatori","Tawaramoto","Tenkawa","Tenri","Totsukawa","Uda","Yamatokoriyama","Yamatotakada","Yamazoe","Yoshino"],
    ["Aga","Agano","Awashimaura","Gosen","Itoigawa","Izumozaki","Joetsu","Kamo","Kariwa","Kashiwazaki","Minamiuonuma","Mitsuke","Murakami","Myoko","Nagaoka","NiigataSouth","Niigata","Ojiya","Sado","Sanjo","Seiro","Sekikawa","Shibata","Tagami","Tainai","Tokamachi","Tsubame","Tsunan","Uonuma","Yahiko","Yuzawa"],
    ["Beppu","BungoOhno","Bungotakada","Hiji","Hita","Kitsuki","Kokonoe","Kunisaki","Kusu","Nakatsu","Oita","Saiki","Taketa","Tsukumi","Usa","Usuki","Yufu"],
    ["Akaiwa","Asakuchi","Bizen","Hayashima","Ibara","Kagamino","Kasaoka","Kibichuo","Kumenan","Kurashiki","Maniwa","Mimasaka","Misaki","Nagi","Niimi","Nishiawakura","Okayama","Satosho","Setouchi","Shinjo","Shoo","Soja","Takahashi","Tamano","Tsuyama","Wake","Yakage"],
    ["Chihayaakasaka","Daito","Fujidera","Habikino","Hannan","Higashiosaka","Hirakita","Ibaraki","Ikeda","Izumi","Izumiotsu","Izumisano","Kadoma","Kaizuka","Kanan","Kashiwara","Katano","Kawachinagano","Kishiwada","Kumatori","Matsubara","Minoh","Misaki","Moriguchi","Neyagawa","Nose","Osaka","Osakasayama","Sakai","Sennan","Settsu","Shijonawate","Shimamoto","Suita","Tadaoka","Taishi","Tajiri","Takaishi","Takatsuki","Tondabayashi","Toyonaka","Toyono","Yao"],
    ["Arita","Genkai","Imari","Kamimine","Kanzaki","Karatsu","Kashima","Kiyama","Kouhoku","Miyaki","Ogi","Omachi","Saga","Shiroishi","Takeo","Taku","Tara","Tosu","Ureshino","Yoshinogari"],
    ["Ageo","Asaka","Chichibu","Fujimi","Fujimino","Fukaya","Gyoda","Hanno","Hanyu","Hasuda","Hatoyama","Hidaka","Higashichichibu","Higashimatsuyama","Honjo","Ina","Iruma","Kamikawa","Kamisato","Kasukabe","Kawagoe","Kawaguchi","Kawajima","Kazo","Kitamoto","Koshigaya","Kounosu","Kuki","Kumagaya","Matsubushi","Minano","MisatoKodama","Misato","Miyashiro","Miyoshi","Moroyama","Nagatoro","Namegawa","Niiza","Ogano","Ogawa","Ogose","Okegawa","Ranzan","Saitama","Sakado","Satte","Sayama","Shiki","Shiraoka","Soka","Sugito","Toda","Tokigawa","Tokorozawa","Tsurugashima","Wako","Warabi","Yashio","Yokoze","Yorii","Yoshikawa","Yoshimi"],
    ["Aisho","Higashiomi","Hikone","Hino","Koka","Konan","Koura","Kusatsu","Maibara","Moriyama","Nagahama","Omihachiman","Otsu","Ritto","Ryuoh","Taga","Takashima","Toyosato","Yasu"],
    ["Gotsu","Hamada","Iinan","Izumo","Kawamoto","Masuda","Matsue","Misato","Oda","Ohnan","Okuizumo","Tsuwano","Unnan","Yasugi","Yoshika"],
    ["Atami","Fuji","Fujieda","Fujinomiya","Fukuroi","Gotemba","Hamamatsu","Higashiizu","Ito","Iwata","Izu","Izunokuni","Kakegawa","Kannami","Kawanehon","Kawazu","Kikugawa","Kosai","Makinohara","Matsuzaki","Minamiizu","Mishima","Mori","Nagaizumi","Nishiizu","Numazu","Omaezaki","Oyama","Shimada","Shimizu","Shimoda","Shizuoka","Susono","Yaizu","Yoshida"],
    ["Ashikaga","Haga","Ichikai","Kaminokawa","Kanuma","Mashiko","Mibu","Moka","Motegi","Nakagawa","Nasu","Nasukarasuyama","Nasushiobara","Nikko","Nogi","Ohtawara","Oyama","Sakura","Sano","Shimotsuke","Shioya","Takanezawa","Tochigi","Utsunomiya","Yaita"],
    ["Aizumi","Anan","Awa","Higashimiyoshi","Ishii","Itano","Kaiyo","Kamiita","Kamikatsu","Kamiyama","Katsuura","Kitajima","Komatsushima","Matsushige","Mima","Minami","MiyoshiNorth","MiyoshiSouth","Mugi","Naka","Naruto","Sanagochi","Tokushima","Tsurugi","Yoshinogawa"],
    ["Akiruno","Akishima","Chofu","Fuchu","Fussa","Hachioji","Hamura","Higashikurume","Higashimurayama","Higashiyamato","Hino","Hinode","Hinohara","Inagi","Kiyose","Kodaira","Koganei","Kokubunji","Komae","Kunitachi","Machida","Mitaka","Mizuho","Musashimurayama","Musashino","Nishitokyo","Okutama","Ome","Tachikawa","Tama","Tokyo"],
    ["Chizu","Daisen","Hiezu","Hino","Hokuei","Houki","Iwami","Kofu","Kotoura","Kurayoshi","Misasa","Nanbu","Nichinan","Sakaiminato","Tottori","Wakasa","Yazu","Yonago","Yurihama"],
    ["Asahi","Funahashi","Himi","Imizu","Kamiichi","Kurobe","Namerikawa","Nanto","Nyuzen","Oyabe","Takaoka","Tateyama","Tonami","Toyama","Uozu"],
    ["Arida","Aridakawa","Gobo","Hashimoto","Hidaka","Hidakagawa","Hirokawa","Inami","Iwade","Kainan","Kamitonda","Katsuragi","Kimino","Kinokawa","Kitayama","Koya","Kozagawa","Kudoyama","Kushimoto","Mihama","Minabe","Nachikatsuura","Shingu","Shurahama","Susami","Taiji","Tanabe","Wakayama","Yuasa","Yura"],
    ["Asahi","Funagata","Higashine","Iide","Kahoku","Kaminoyama","Kaneyama","Kawanishi","Mamurogawa","Mikawa","Mogami","Murayama","Nagai","Nakayama","Nanyo","Nishikawa","Obanazawa","Oe","Oguni","Ohkura","Oishida","Sagae","Sakata","Sakegawa","Shinjo","Shirataka","Shonai","Takahata","Tendo","Tozawa","Tsuruoka","Yamagata","Yamanobe","Yonezawa","Yuza"],
    ["Abu","Hagi","Hikari","Hirao","Hofu","Iwakuni","Kaminoseki","Kudamatsu","Mine","Nagato","SanyoOnoda","Shimonoseki","Shunan","SuoOshima","Tabuse","Ube","Waki","Yamaguchi","Yanai"],
    ["Chuo","Doshi","Fuefuki","Fujikawa","Fujikawaguchiko","Fujiyoshida","Hayakawa","Hokuto","Ichikawamisato","Kai","Kofu","Koshu","Kosuge","MinamiAlps","Minobu","Nanbu","Narusawa","Nirasaki","Nishikatsura","Oshino","Otsuki","Showa","Tabayama","Tsuru","Uenohara","Yamanakako","Yamanashi"]
];



function Start(){

    PrefectureInit();
}

function PrefectureInit(){

    for(let a = 0; a < PrefArray.length; a++){

        //Gets DistrictSVGs for Prefecture in Array
        var LoopPrefArray = Array.from(
            document.getElementsByClassName(PrefArray[a]+"D")
        );

        //Sets a temporary ID for every District in Prefecture
        for(let b = 0; b < LoopPrefArray.length; b++){
            LoopPrefArray[b].setAttribute("id",PrefArray[a]+"_"+b)
        }
    }
}